/// <reference types="cypress" />'
import elements from '../../support/pageElements'
import threeGlovesResponse from '../../fixtures/return/inStoreReturns/addReturnItems/threeBaseballGloves.json'

context('Returns Lookup by Loyalty tests', () => {
  
    const tags = new elements()
    const loyaltyPhoneNumber = Cypress.env().phoneNumberSingleResult

    beforeEach(() => {
      cy.launchPageLoggedIn()
    })

    it('Test 1: Loyalty Lookup by Phone Number view has correct verbiage and buttons', () => {
      tags.returnsFooterButton().click()
      tags.returnsLookupGenericButton().should('be.visible').and('have.text', 'NEXT')
      tags.returnsLookupGenericButton().click()
      tags.loyaltyReturnLookupCloseButton().should('be.visible')
      tags.returnGenericNumberEntryField().should('be.visible')
      tags.noReceiptReturnLink().should('be.visible').and('have.text', 'No Receipt Available')
    })

    it('Test 2: Entering a loyalty phone number associated with one account goes directly to orders view', () => {
      tags.returnsFooterButton().click()
      tags.returnGenericNumberEntryField().click().type(loyaltyPhoneNumber)
      cy.loyaltyLookupReturnPhoneOneResult()
      tags.loyaltyReturnLookupFirstResult().should('be.visible')
        .and('have.text', '6/29/2022 - $160.47Order #: 20220629008883800032NON-PROD STORE')
      tags.loyaltyReturnLookupSecondResult().should('be.visible')
        .and('have.text', '6/29/2022 - $187.23Order #: 20220629008883800033NON-PROD STORE')
      tags.loyaltyReturnLookupThirdResult().should('be.visible')
        .and('have.text', '6/30/2022 - $641.98Order #: 20220629008883800034NON-PROD STORE')
    })

    it('Test 3: Return Items modal should contain correct verbiage and buttons', () => {
      tags.returnsFooterButton().click()
      tags.returnGenericNumberEntryField().click().type(loyaltyPhoneNumber)
      cy.loyaltyLookupReturnPhoneOneResult()
      tags.loyaltyReturnLookupFirstResult().click()
      tags.loyaltyReturnLookupModalTitle().should('have.text', 'Return Items - Rolyat Nai')
      tags.loyaltyReturnLookupCloseButton().should('be.visible')
      tags.backButton().should('be.visible')
      tags.loyaltyReturnOrderDetails().should('have.text', '6/29/2022 - $160.47Order #: 20220629008883800032NON-PROD STORE')
      tags.loyaltyReturnModal().should('be.visible')
      tags.loyaltyReturnLookupSelectAllLink().should('be.visible').and('have.text', 'Select All')
      tags.loyaltyReturnLookupItem1Description().should('be.visible').and('have.text', 'Rawlings 12"  Youth Highlight Series Glove 2019')
      tags.loyaltyReturnLookupItem1Price().should('be.visible').and('have.text', '49.99')
      tags.loyaltyReturnLookupItem1UPC().should('be.visible').and('have.text', '083321578120')
      tags.loyaltyReturnLookupItem2Description().should('be.visible').and('have.text', 'Rawlings 12"  Youth Highlight Series Glove 2019')
      tags.loyaltyReturnLookupItem2Price().should('be.visible').and('have.text', '49.99')
      tags.loyaltyReturnLookupItem2UPC().should('be.visible').and('have.text', '083321578120')
      tags.loyaltyReturnLookupItem3Description().should('be.visible').and('have.text', 'Rawlings 12"  Youth Highlight Series Glove 2019')
      tags.loyaltyReturnLookupItem3Price().should('be.visible').and('have.text', '49.99')
      tags.loyaltyReturnLookupItem3UPC().should('be.visible').and('have.text', '083321578120')
      tags.loyaltyReturnLookupSubmitButton().should('be.visible')
    })

    it('Test 4: Able to start a return transaction from Return Items modal', () => {
      tags.returnsFooterButton().click()
      tags.returnGenericNumberEntryField().click().type(loyaltyPhoneNumber)
      cy.loyaltyLookupReturnPhoneOneResult()
      tags.loyaltyReturnLookupFirstResult().click()
      tags.loyaltyReturnLookupSelectAllLink().click()
      cy.addLoyaltyReturnItems(threeGlovesResponse)
      tags.loyaltyGoldTier().should('be.visible')
      tags.loyaltySelectedAthlete().should('be.visible').and('contain.text', 'Rolyat Nai')
      tags.loyaltyPointsBalance().should('be.visible').and('contain.text', 'Points Balance: 353')
      tags.priceItem1().should('have.text', '-49.99')
      tags.priceItem2().should('have.text', '-49.99')
      tags.priceItem3().should('have.text', '-49.99')
      tags.couponsAndDiscounts().should('have.text', '0.00')
      tags.subtotal().should('have.text', '-149.97')
      tags.taxes().should('have.text', '-10.50')
      tags.total().should('have.text', '-160.47')
    })

    it('Test 5: Loyalty phone number with multiple accounts', () => {
      tags.returnsFooterButton().click()
      tags.returnGenericNumberEntryField().click().type(loyaltyPhoneNumber)
      cy.loyaltyLookupReturnPhoneTwoResults()
      tags.loyaltyReturnLookupCustomerFirstResult().should('be.visible')
        .and('have.text', 'Rolyat Naiit@hotmail.com3213 JohnWayne StreetErie, PA 16508')
      tags.loyaltyReturnLookupCustomerSecondResult().should('be.visible')
        .and('have.text', 'Rolyat Naiit@hotmail.com3213 JohnWayne StreetErie, PA 16508')
      tags.loyaltyReturnLookupThirdResult().should('not.exist')
    })

    it('Test 6: Choosing a loyalty account takes you to the orders view', () => {
      tags.returnsFooterButton().click()
      tags.returnGenericNumberEntryField().click().type(loyaltyPhoneNumber)
      cy.loyaltyLookupReturnPhoneTwoResults()
      cy.intercept('**/Returns/Loyalty/L017B23WK6CS', { fixture: 'return/loyaltyLookupReturnsResponse' }).as('loyaltyLookupReturnsResults')
      tags.loyaltyReturnLookupCustomerFirstResult().click()
      cy.wait('@loyaltyLookupReturnsResults')
      tags.loyaltyReturnLookupFirstResult().should('be.visible')
        .and('have.text', '6/29/2022 - $160.47Order #: 20220629008883800032NON-PROD STORE')
      tags.loyaltyReturnLookupSecondResult().should('be.visible')
        .and('have.text', '6/29/2022 - $187.23Order #: 20220629008883800033NON-PROD STORE')
      tags.loyaltyReturnLookupThirdResult().should('be.visible')
        .and('have.text', '6/30/2022 - $641.98Order #: 20220629008883800034NON-PROD STORE')
    })


    it('Test 7: Can filter orders by UPC', () => {
      tags.returnsFooterButton().click()
      tags.returnGenericNumberEntryField().click().type(loyaltyPhoneNumber)
      cy.loyaltyLookupReturnPhoneOneResult()
      tags.loyaltyReturnLookupFirstResult().should('be.visible')
      tags.loyaltyReturnLookupSecondResult().should('be.visible')
      tags.loyaltyReturnLookupThirdResult().should('be.visible')
      tags.noReceiptManualInputField().type('038675142275{enter}')
      tags.athleteOrderUpcFirstChip().should('be.visible').and('have.text', '038675142275')
      tags.loyaltyReturnLookupFirstResult().should('be.visible')
        .and('have.text', '6/30/2022 - $641.98Order #: 20220629008883800034NON-PROD STORE')
      tags.loyaltyReturnLookupSecondResult().should('not.exist')
      tags.loyaltyReturnLookupThirdResult().should('not.exist')
      tags.noReceiptManualInputField().type('083321578120{enter}')
      tags.athleteOrderUpcSecondChip().should('be.visible').and('have.text', '083321578120')
      tags.loyaltyReturnLookupFirstResult().should('be.visible')
        .and('have.text', '6/29/2022 - $160.47Order #: 20220629008883800032NON-PROD STORE')
      tags.loyaltyReturnLookupSecondResult().should('be.visible')
        .and('have.text', '6/30/2022 - $641.98Order #: 20220629008883800034NON-PROD STORE')
      tags.loyaltyReturnLookupThirdResult().should('not.exist')
      tags.athleteOrderUpcSecondChipCloseButton().click()
      tags.athleteOrderUpcSecondChip().should('not.exist')
      tags.athleteOrderUpcFirstChip().should('be.visible').and('have.text', '038675142275')
      tags.loyaltyReturnLookupFirstResult().should('be.visible')
        .and('have.text', '6/30/2022 - $641.98Order #: 20220629008883800034NON-PROD STORE')
      tags.loyaltyReturnLookupSecondResult().should('not.exist')
      tags.athleteOrderUpcFirstChipCloseButton().click()
      tags.athleteOrderUpcFirstChip().should('not.exist')
      tags.loyaltyReturnLookupFirstResult().should('be.visible')
      tags.loyaltyReturnLookupSecondResult().should('be.visible')
      tags.loyaltyReturnLookupThirdResult().should('be.visible')
    })

    it('Test 8: Can sort orders by newest to oldest', () => {
      tags.returnsFooterButton().click()
      tags.returnGenericNumberEntryField().click().type(loyaltyPhoneNumber)
      cy.loyaltyLookupReturnPhoneOneResult()
      tags.loyaltyReturnLookupFirstResult().should('be.visible')
        .and('have.text', '6/29/2022 - $160.47Order #: 20220629008883800032NON-PROD STORE')
      tags.loyaltyReturnLookupSecondResult().should('be.visible')
        .and('have.text', '6/29/2022 - $187.23Order #: 20220629008883800033NON-PROD STORE')
      tags.loyaltyReturnLookupThirdResult().should('be.visible')
        .and('have.text', '6/30/2022 - $641.98Order #: 20220629008883800034NON-PROD STORE')
      tags.returnLookupByLoyaltySortButton().should('have.text', 'Oldest to Newest').click()
      tags.loyaltyReturnLookupFirstResult().should('be.visible')
        .and('have.text', '6/30/2022 - $641.98Order #: 20220629008883800034NON-PROD STORE')
      tags.loyaltyReturnLookupSecondResult().should('be.visible')
        .and('have.text', '6/29/2022 - $160.47Order #: 20220629008883800032NON-PROD STORE')
      tags.loyaltyReturnLookupThirdResult().should('be.visible')
        .and('have.text', '6/29/2022 - $187.23Order #: 20220629008883800033NON-PROD STORE')
      tags.returnLookupByLoyaltySortButton().should('have.text', 'Newest to Oldest').click()
      tags.loyaltyReturnLookupFirstResult().should('be.visible')
        .and('have.text', '6/29/2022 - $160.47Order #: 20220629008883800032NON-PROD STORE')
      tags.loyaltyReturnLookupSecondResult().should('be.visible')
        .and('have.text', '6/29/2022 - $187.23Order #: 20220629008883800033NON-PROD STORE')
      tags.loyaltyReturnLookupThirdResult().should('be.visible')
        .and('have.text', '6/30/2022 - $641.98Order #: 20220629008883800034NON-PROD STORE')
      tags.returnLookupByLoyaltySortButton().should('have.text', 'Oldest to Newest')
    })

})